### DISCUSSION TITLE
Missprint of table styles

### DISCUSSION THREAD

**Discussion by d8corp** [npm/feedback#463] [Website] [answered]
I hope this is not a feature!

On a page of a package, in the readme zone, each table has `display: block` and `width: 100%`.

Find it by the selectors `.markdown table` and `._6d9832ac table`
```css
.markdown table {
    display: block;    /* remove here */
    white-space: normal;
    overflow-x: auto;
    width: 100%;    /* remove here */
    border-collapse: collapse;
    border-spacing: 0px;
}
._6d9832ac table {
    display: block;    /* remove here */
    white-space: normal;
    overflow-x: auto;
    width: 100%;    /* remove here */
    border-spacing: 0;
    border-collapse: collapse;
    border-bottom: 1px solid #e2e2e2;
}
```

Please just remove it, it's not hard. If it's not a bug then why do you use it?

For example, you can check the difference on [GitHub](https://github.com/d8corp/watch-state) and [NPM](https://www.npmjs.com/package/watch-state)
